---
- hosts: tomcat
  become: yes
  gather_facts: no
  tasks:
  - name: Update
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install Java
    package: 
      name: default-jre
      state: present
  - name: Install Tomcat
    get_url: 
      url: http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
      dest: /root
      mode: 0440
  - name: Untar Tomcat
    unarchive:
      src: /root/apache-tomcat-9.0.10.tar.gz
      dest: /etc
      copy: no
  - name: Create Deploy user
    user: name=jenkins comment="jenkins" groups="sudo,admin"
    sudo: yes
  - name : sudo
    shell: echo "jenkins ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
    args:
      executable: /bin/bash  
  - name: create ssh directory
    file:
      path: /home/jenkins/.ssh
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0700
  - name: create authorized file
    file: 
      path: /home/jenkins/.ssh/authorized_keys
      owner: jenkins
      group: jenkins
      mode: 0600
  - name: start
    command: sh /etc/apache-tomcat-9.0.10/bin/startup.sh
    become: true
    become_user: root
